### PR TITLE
Module for generating question widgets and callbacks

### PR DESCRIPTION
**Pull request by cmann**
In reviewing and fixing up a number of abandonded notebooks, one of the recurring problems I've noticed is in building multiple choice and text response questions. Lots of repeated code is very common. I've also run into a handful of logic issues, especially with regards to all cells sharing the same global namespace.

This is my initial pass at starting a library of functions to help reduce boilerplate and bugs by handling most of the common logic for notebook creators. See the [readme](https://github.com/callysto/nbplus/blob/nbquestions/nbquestions/README.md) for full details of the functionality. There are a few points I'd like feedback on:

1. Multiple choice allows for 2-5 options. Should this be expanded to a more generic solution that can handle more options?
2. Do the callbacks for success/failure give enough flexibility to notebook creators?
3. Any other processing to provide beyond ignoring whitespace and case for text reponses?
4. I'm far from an expert on higher order functions in python so if there's anything I'm doing wrong or could be doing better please let me know.
5. Any other feedback.

Credit to @MattPalmarin whose code I adapted from one of his notebooks for the multiple choice code in this module.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
My only comment is that this appears to duplicate the functionality of the question generation interface @NathanTipper was working on for CC-165. I'm just not sure where his code was committed. Last update I had from him was that he was rewriting some of the code to use jquery instead of json, and I think his first attempt stalled because he had trouble turning it into a magic function.

**Comment by sean-fitzpatrick** [comment]
Rumour has it we might be able to combine the efforts :-)

**Comment by cmann** [comment]
That'd be great, I'd be happy to collaborate, I hadn't even realized there was similar work going on.

**Comment by ericeasthope** [comment]
Looks good for an initial commit. Please see #66 to follow up on the mentioned collaboration.

**Pull request merged**
